version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python -m frontend.kami