FROM python:latest

WORKDIR /backend

COPY . /backend

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["uvircorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


