FROM python:latest

WORKDIR /backend

COPY . /backend

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

EXPOSE 8000
# Use the PORT environment variable that Cloud Run provides
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $PORT"]